#pragma config(Sensor, in1,    floor1,         sensorReflection)
#pragma config(Sensor, in4,    floor2,         sensorReflection)
#pragma config(Sensor, in7,    floor3,         sensorReflection)
#pragma config(Sensor, dgtl1,  bumpSwitch1,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch2,    sensorTouch)
#pragma config(Sensor, dgtl3,  bumpSwitch3,    sensorTouch)
#pragma config(Motor,  port2,           elevatorMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Move the elevator to the first floor at the beginning of the test.
	startMotor(elevatorMotor,50);
	untilLight(2000, floor1);
	stopMotor(elevatorMotor);

	int currentFloor = 1;
	int goToFloor = 1;

	while(true) //Infinite loop
	{
		// I check the values of the sensors to check for the current floor (position of the elevator)
		if (SensorValue[floor1]<2400) currentFloor = 1;
		if (SensorValue[floor2]<2400) currentFloor = 2;
		if (SensorValue[floor3]<2400) currentFloor = 3;

		// I check if the user press a button
		if (SensorValue[bumpSwitch1]==1) goToFloor = 1;
		if (SensorValue[bumpSwitch2]==1) goToFloor = 2;
		if (SensorValue[bumpSwitch3]==1) goToFloor = 3;

		// Check if I need to move the elevator UP, DOWN or STOP the elevator
		if (currentFloor == goToFloor)
		{
			stopMotor(elevatorMotor);
		}
		else if (currentFloor < goToFloor) // Let's go UP
		{
			startMotor(elevatorMotor, 50);
		}
		else if (currentFloor > goToFloor) // Let's go DOWN
		{
			startMotor(elevatorMotor, -50);
		}
	}

}
